<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class Mentor extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable, HasRoles;

    /**
     * @var string[]
     */
    protected $fillable = [
        'slug',
        'name',
        'email',
        'username',
        'profile_image',
        'code_mobile',
        'mobile_number',
        'address',
        'city',
        'state',
        'experience',
        'nationality',
        'status',
        'files',
        'is_active',
        'last_active_at'
    ];

    protected string $guard_name = 'mentor';


    protected $casts = [
        'status' => 'array',
        'is_active' => 'boolean',
        'files' => 'array',
        'last_active_at' => 'datetime'
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($mentor) {
            $mentor->slug = Str::slug($mentor->name) . '-' . Str::random(10);
        });
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_mentors')
            ->withTimestamps();
    }


    public function comments()
    {
        return $this->hasMany(Comment::class, "user");
    }
}
