<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\HigherOrderWhenProxy;
use Illuminate\Support\Str;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;


class Student extends Authenticatable
{
    use SoftDeletes, HasApiTokens, Notifiable, HasRoles;

    protected $fillable = [
        'slug',
        'email',
        'username',
        'full_name',
        'profile_image',
        'university_name',
        'university_major',
        'code_mobile',
        'mobile_number',
        'teacher_collage',
        'files',
        'is_active',
        'gender'
    ];

    protected string $guard_name = 'student';

    protected $casts = [
        'is_active' => 'boolean',
        'files' => 'array',
        'last_active_at' => 'datetime'
    ];

    # Broken Access Control
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($student) {
            $student->slug = Str::slug($student->full_name) . '-' . Str::random(10);
        });
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public static function searchStudents(Builder $query, string $searchTerm): Builder
    {
        return $query->where(function ($query) use ($searchTerm) {
            $query->where('full_name', 'LIKE', "%{$searchTerm}%")
                ->orWhere('email', 'like', "%{$searchTerm}%")
                ->orWhere('mobile_number', 'like', "%{$searchTerm}%")
                ->orWhere('university_name', 'like', "%{$searchTerm}%")
                ->orWhere('university_major', 'like', "%{$searchTerm}%")
                ->orWhere('teacher_collage', 'like', "%{$searchTerm}%");
        });
    }


    public function filterStudents(Builder $query, array $filters): Builder|HigherOrderWhenProxy
    {
        return $query

            // =========================
            // Filtering
            // =========================

            ->when(data_get($filters, 'full_name'), function ($q, $value) {
                $q->where('full_name', 'like', "%{$value}%");
            })
            ->when($filters['email'] ?? null, function ($q, $value) {
                $q->where('email', 'like', "%{$value}%");
            })
            ->when($filters['university_name'] ?? null, function ($q, $value) {
                $q->where('university_name', $value);
            })
            ->when($filters['university_major'] ?? null, function ($q, $value) {
                $q->where('university_major', $value);
            })
            ->when($filters['gender'] ?? null, function ($q, $value) {
                $q->where('gender', $value);
            })
            ->when(isset($filters['is_active']), function ($q) use ($filters) {
                $q->where('is_active', $filters['is_active']);
            })

            // Filter by course (Relation)
            ->when($filters['course_id'] ?? null, function ($q, $value) {
                $q->whereHas('courses', function ($query) use ($value) {
                    $query->where('courses.id', $value);
                });
            })

            // =========================
            // Sorting
            // =========================

            ->when($filters['sort_by'] ?? null, function ($q, $sortBy) use ($filters) {

                $allowedSorts = ['created_at', 'full_name', 'email'];

                if (in_array($sortBy, $allowedSorts)) {
                    $order = $filters['order'] ?? 'desc';
                    $q->orderBy($sortBy, $order);
                }
            }, function ($q) {
                // default sorting
                $q->orderBy('created_at', 'desc');
            })

            // =========================
            // Eager Loading
            // =========================
            ->with('courses');
    }

    public function courses()
    {
        return $this->belongsToMany(Course::class, 'course_students');
    }

    public function submissions()
    {
        return $this->hasMany(TaskSubmission::class);
    }

    public function comments()
    {
        return $this->hasMany(Comment::class, "user");
    }

    public function videoProgress()
    {
        return $this->hasMany(StudentVideoProgress::class);
    }


}
