<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class SuccessStories extends Model
{
    protected $table = 'success_stories';

    protected $fillable = [
        'name',
        'description',
        'image_url',
        'video_url',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::creating(function ($successStory) {
            $successStory->slug = Str::slug($successStory->name) . '-' . Str::random(10);
        });
    }

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }
}
